### PR TITLE
Fix Markdown heading

### PR DESCRIPTION
**Pull request by devenney**
Also removes some unnecessary whitespace

### CODE REVIEW

**Comment by devenney** [comment]
Paging @barryor @jexh.

**Comment by devenney** [comment]
@ivolz @skiph This is clogging up my tools, will decline in a week. Act fast or lose the extremely complicated work held within! :eyes:

**Comment by ivolz** [comment]
It’s only been two years since the PR. How are you doing?
This email and any attachments are sent in confidence and are not intended to be read by any person other than an intended recipient. The recipient is responsible for conducting the appropriate virus checks and whilst appropriate security measures are in place, we give no warranty, express or implied, that this email is free of viruses or that its transmission has been secure.

If you receive this email in error, please contact us on privacy@criticalblue.com <mailto:privacy@criticalblue.com> and permanently delete this email. Any use, copying or dissemination of this email or any information contained in it to anyone other than an intended recipient is prohibited.

Any and all communications sent to us may be monitored and/or stored by us to ensure compliance with relevant legislation, rules, and policies. All communications are handled in full compliance with current data protection legislation including, but not limited to, EU Regulation 2016/679 General Data Protection Regulation (“GDPR”). For further information please refer to our Privacy Policy <https://www.approov.io/privacy/>.

**Comment by ivolz** [comment]
> @ivolz @skiph This is clogging up my tools, will decline in a week. Act fast or lose the extremely complicated work held within! 👀

Thanks for reminding me.

**Pull request merged**
